FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p backend
COPY backend/prompt_template_desc.py backend/
COPY backend/prompt_templates_short.py backend/

COPY mcp-server ./mcp-server

RUN touch backend/__init__.py

EXPOSE 8000

CMD ["python", "-m", "mcp-server.server"]

